version: '3'
services:
  creator-node-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_creator_node
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '${CREATOR_NODE_DB_HOST_PORT}:5432'
    networks:
      - audius_dev
  creator-node:
    build: ../.
    command: sh -c './scripts/endpoint.sh'
    depends_on:
      - creator-node-db
      - creator-node-redis
    environment:
      - redisHost=${COMPOSE_PROJECT_NAME}_creator-node-redis_1
      - dbUrl=postgres://postgres:postgres@${COMPOSE_PROJECT_NAME}_creator-node-db_1:5432/audius_creator_node
      - WAIT_HOSTS=${COMPOSE_PROJECT_NAME}_creator-node-db_1:5432, ${COMPOSE_PROJECT_NAME}_creator-node-redis_1:6379
      - spOwnerWalletIndex=${SP_OWNER_WALLET_INDEX}
    env_file:
      - ./env/base.env
    ports:
      - '${CREATOR_NODE_HOST_PORT}:4000'
      - 20000
    volumes:
      - file_storage:/file_storage
      - ..:/usr/src/app
      # Prevent hiding node_modules on container with host volume
      # From https://github.com/barrysteyn/node-scrypt/issues/148
      - /usr/src/app/node_modules
    networks:
      - audius_dev
  creator-node-redis:
    image: redis:5.0.4
    ports:
      - '${CREATOR_NODE_REDIS_HOST_PORT}:6379'
    networks:
      - audius_dev

volumes:
  postgres_data:
  file_storage:

networks:
  audius_dev:
    external: true